### ISSUE TITLE
Spurious Minibuffer Output Indenting Region

### ISSUE THREAD

**Issue by creichert** [creichert/magit-gh-issues#2]
"Indenting Region" is printed to the console in rapid succession for each issue. The text formatting for each issue has been a hack so far so it's time for an improvement.

**Comment by CodyReichert** [comment]
I think this was fixed in the update to the new magit a while back: https://github.com/creichert/magit-gh-issues/commit/a2301a6cabc703fde67267f4676912b682aacc5c
